from cheat_bot.repository.s3_system import S3System
from cheat_bot.repository.user_system import UserSystem
from cheat_bot.repository.sources.file_repository.file_repository import FileRepository
from cheat_bot.repository.sources.user_system.user_system_postgres import UserSystemPostgres
